export const SECTION = Object.freeze({
  HOME: "home",
  COMPONENTS: "components",
  // ACCOUNT_PLATFORM_SETTINGS: "account_platform_settings",
});

export const DATEFORMAT = Object.freeze({
  DATE: "MMM. dd, yyyy",
  TIME: "hh:mm aa",
  DATE_TIME: "MMM. dd, yyyy hh:mm aa",
  DATE_TIME_TZ: "MMM. dd, yyyy hh:mm aa XXXX",
});

export const NAMES = [
  {
    id: 1,
    name: "Addy",
  },
  {
    id: 2,
    name: "Celine",
  },
  {
    id: 3,
    name: "Marjon",
  },
  {
    id: 4,
    name: "Mary",
  },
];

export const COUNTRY = [
  {
    id: 1,
    countryName: "Philippines",
  },
  {
    id: 2,
    countryName: "Ukraine",
  },
  {
    id: 2,
    countryName: "Netherlands",
  },
  {
    id: 2,
    countryName: "Japan",
  },
  {
    id: 2,
    countryName: "America",
  },
];

export const DEPARTMENTS = [
  {
    id: 1,
    name: "OSD Moderation",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "OSD Moderation",
  },
  {
    id: 4,
    name: "Product Development Department",
    status: 1,
    created_at: null,
    updated_at: "2022-08-31T05:19:34.000000Z",
    slug: "Product Development Department",
  },
  {
    id: 5,
    name: "Information Technology & Development",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Information Technology &amp; Development",
  },
  {
    id: 6,
    name: "Offline Services Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Offline Services Department",
  },
  {
    id: 7,
    name: "Live Services Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Live Services Department",
  },
  {
    id: 8,
    name: "Finance Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Finance Department",
  },
  {
    id: 9,
    name: "Human Resource and Administrative Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Human Resource and Administrative Department",
  },
  {
    id: 11,
    name: "Customer Experience Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Customer Experience Department",
  },
  {
    id: 14,
    name: "Online Management Personnel",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Online Management Personnel",
  },
  {
    id: 16,
    name: "Online Support",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Online Support",
  },
  {
    id: 17,
    name: "Disney Productions Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Disney Productions Department",
  },
  {
    id: 18,
    name: "English Messaging",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "English Messaging",
  },
  {
    id: 19,
    name: "Production Recruitment Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Production Recruitment Department",
  },
  {
    id: 20,
    name: "External Affairs and Production Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "External Affairs and Production Department",
  },
  {
    id: 21,
    name: "Training & Quality Assurance Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Training &amp; Quality Assurance Department",
  },
  {
    id: 22,
    name: "Corporate Image & Branding",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Corporate Image &amp; Branding",
  },
  {
    id: 23,
    name: "NMS Cares",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "NMS Cares",
  },
  {
    id: 24,
    name: "Sales & Marketing",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Sales &amp; Marketing",
  },
  {
    id: 25,
    name: "FL Production Department Management",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "FL Production Department Management",
  },
  {
    id: 26,
    name: "Employee Engagement and Retention",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Employee Engagement and Retention",
  },
  {
    id: 27,
    name: "English Messaging Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "English Messaging Department",
  },
  {
    id: 28,
    name: "Jeemo PJ",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Jeemo PJ",
  },
  {
    id: 29,
    name: "OSD Support",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "OSD Support",
  },
  {
    id: 30,
    name: "Production Department Support",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Production Department Support",
  },
  {
    id: 31,
    name: "Outbound Support",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Outbound Support",
  },
  {
    id: 32,
    name: "OSD SEO",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "OSD SEO",
  },
  {
    id: 33,
    name: "OSD Billing",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "OSD Billing",
  },
  {
    id: 34,
    name: "OSD SEO Beta",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "OSD SEO Beta",
  },
  {
    id: 35,
    name: "Digital Content",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Digital Content",
  },
  {
    id: 36,
    name: "Online Support Services Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Online Support Services Department",
  },
  {
    id: 37,
    name: "Client Support Services Management Team",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Client Support Services Management Team",
  },
  {
    id: 38,
    name: "Marketing Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Marketing Department",
  },
  {
    id: 39,
    name: "Sales Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Sales Department",
  },
  {
    id: 40,
    name: "FTHB - English Messaging Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "FTHB - English Messaging Department",
  },
  {
    id: 41,
    name: "Trainee",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Trainee",
  },
  {
    id: 42,
    name: "Global I.T. and Products Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Global I.T. and Products Department",
  },
  {
    id: 43,
    name: "TIRO Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "TIRO Department",
  },
  {
    id: 44,
    name: "NMS Production",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "NMS Production",
  },
  {
    id: 45,
    name: "NMS Officers",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "NMS Officers",
  },
  {
    id: 46,
    name: "Chekkee Moderation Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Chekkee Moderation Department",
  },
  {
    id: 47,
    name: "Sales and Marketing Department",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Sales and Marketing Department",
  },
  {
    id: 48,
    name: "Non-English Services Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Non-English Services Department",
  },
  {
    id: 49,
    name: "English Messaging - I.M. Live Section",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "English Messaging - I.M. Live Section",
  },
  {
    id: 50,
    name: "Product Management",
    status: 1,
    created_at: null,
    updated_at: null,
    slug: "Product Management",
  },
  {
    id: 51,
    name: "Messaging Services Department",
    status: 0,
    created_at: null,
    updated_at: null,
    slug: "Messaging Services Department",
  },
  {
    id: 52,
    name: "OSD Moderation — Moderationv3",
    status: 1,
    created_at: "2022-07-19T06:42:38.000000Z",
    updated_at: "2022-07-19T06:42:38.000000Z",
    slug: "osd-moderation-—-moderationv3",
  },
  {
    id: 53,
    name: "Freelance Chat Support",
    status: 1,
    created_at: "2022-07-22T07:04:05.000000Z",
    updated_at: "2022-07-22T07:04:05.000000Z",
    slug: "freelance-chat-support",
  },
];
